//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class historiqueKPI
    {
        public decimal idHistoriqueKPI { get; set; }
        public decimal valeurHisKPI { get; set; }
        public System.DateTime dateHisKPI { get; set; }
        public decimal idKPI { get; set; }
        public decimal idReference { get; set; }
    
        public virtual KPI KPI { get; set; }
        public virtual reference reference { get; set; }
    }
}
