//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class historiqueConnexion
    {
        public decimal idSession { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime stopTime { get; set; }
        public string Calling { get; set; }
        public string numSequence { get; set; }
    }
}
