//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class topnetBDEntities : DbContext
    {
        public topnetBDEntities()
            : base("name=topnetBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<historiqueConnexion> historiqueConnexion { get; set; }
        public virtual DbSet<historiqueKPI> historiqueKPI { get; set; }
        public virtual DbSet<KPI> KPI { get; set; }
        public virtual DbSet<ligneADSL> ligneADSL { get; set; }
        public virtual DbSet<modem> modem { get; set; }
        public virtual DbSet<motif> motif { get; set; }
        public virtual DbSet<Panne> Panne { get; set; }
        public virtual DbSet<panneLigneADSL> panneLigneADSL { get; set; }
        public virtual DbSet<reference> reference { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
        public virtual DbSet<typeReseau> typeReseau { get; set; }
        public virtual DbSet<userLigneADSL> userLigneADSL { get; set; }
    }
}
