//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class modem
    {
        public decimal numSerieModem { get; set; }
        public string marqueModem { get; set; }
        public decimal debitModem { get; set; }
        public System.DateTime dateEchangeModem { get; set; }
        public string modelModem { get; set; }
        public string numSequence { get; set; }
    }
}
