//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Panne()
        {
            this.panneLigneADSL = new HashSet<panneLigneADSL>();
        }
    
        public decimal idPanne { get; set; }
        public string typePanne { get; set; }
        public string valeurPanne { get; set; }
        public System.DateTime debutPanne { get; set; }
        public System.DateTime finPanne { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<panneLigneADSL> panneLigneADSL { get; set; }
    }
}
