//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class panneLigneADSL
    {
        public decimal idPanne { get; set; }
        public string numSequence { get; set; }
    
        public virtual ligneADSL ligneADSL { get; set; }
        public virtual Panne Panne { get; set; }
        public virtual panneLigneADSL panneLigneADSL1 { get; set; }
        public virtual panneLigneADSL panneLigneADSL2 { get; set; }
    }
}
