//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class historiqueSession
    {
        public int idSession { get; set; }
        public Nullable<System.DateTime> dateDebutSession { get; set; }
        public Nullable<System.DateTime> dateFinSession { get; set; }
        public string nasIdentifier { get; set; }
        public string calling { get; set; }
        public int numSequence { get; set; }
    
        public virtual ligneADSL ligneADSL { get; set; }
    }
}
