//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class historiqueKPI
    {
        public int idKPI { get; set; }
        public Nullable<double> valeurKPI { get; set; }
        public Nullable<System.DateTime> dateHistoriqueKPI { get; set; }
        public Nullable<int> dureeKPI { get; set; }
        public int numSequence { get; set; }
    
        public virtual KPI KPI { get; set; }
        public virtual ligneADSL ligneADSL { get; set; }
    }
}
