//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class localite
    {
        public int idLocalite { get; set; }
        public int idDeligation { get; set; }
        public string nomLocalite { get; set; }
    
        public virtual deligation deligation { get; set; }
    }
}
