//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class modem
    {
        public int numSerieModem { get; set; }
        public string marque { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<System.DateTime> dateEchange { get; set; }
        public Nullable<int> model { get; set; }
        public int numSequence { get; set; }
    
        public virtual ligneADSL ligneADSL { get; set; }
    }
}
