//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int idTicket { get; set; }
        public int idMotif { get; set; }
        public string statut { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int numSequence { get; set; }
    
        public virtual ligneADSL ligneADSL { get; set; }
        public virtual motif motif { get; set; }
    }
}
