//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketGenere
    {
        public string userName { get; set; }
        public int numSequence { get; set; }
        public Nullable<int> nbDeconnexionParJour { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> DureeDeconnection { get; set; }
        public Nullable<System.TimeSpan> DureeConnection { get; set; }
    }
}
