//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailyParameter
    {
        public int numSequence { get; set; }
        public string userName { get; set; }
        public string gouvernerat { get; set; }
        public string delegation { get; set; }
        public string localite { get; set; }
        public Nullable<int> codePostal { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> nbDeconnexionParJour { get; set; }
        public Nullable<int> dureeDeconnexionParJour { get; set; }
        public Nullable<int> dureeConnexionParJour { get; set; }
        public long RowID { get; set; }
    }
}
