//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deligation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deligation()
        {
            this.localites = new HashSet<localite>();
        }
    
        public int idDeligation { get; set; }
        public int idGouvernerat { get; set; }
        public string nomDeligation { get; set; }
    
        public virtual gouvernerat gouvernerat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<localite> localites { get; set; }
    }
}
