//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ligneADSL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ligneADSL()
        {
            this.attenuations = new HashSet<attenuation>();
            this.historiqueSessions = new HashSet<historiqueSession>();
            this.historiqueKPIs = new HashSet<historiqueKPI>();
            this.modems = new HashSet<modem>();
            this.tickets = new HashSet<ticket>();
            this.TypeReseaux = new HashSet<TypeReseau>();
        }
    
        public int numSequence { get; set; }
        public string nature_part_pro_ { get; set; }
        public string userName { get; set; }
        public Nullable<int> debit { get; set; }
        public string gouvernerat { get; set; }
        public string delegation { get; set; }
        public string localite { get; set; }
        public Nullable<int> codePostal { get; set; }
        public string codeGouv { get; set; }
        public Nullable<int> codeClient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attenuation> attenuations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiqueSession> historiqueSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historiqueKPI> historiqueKPIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modem> modems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeReseau> TypeReseaux { get; set; }
    }
}
