//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class topnetDATAEntities : DbContext
    {
        public topnetDATAEntities()
            : base("name=topnetDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<attenuation> attenuations { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<deligation> deligations { get; set; }
        public virtual DbSet<gouvernerat> gouvernerats { get; set; }
        public virtual DbSet<historiqueKPIGlobal> historiqueKPIGlobals { get; set; }
        public virtual DbSet<historiqueSession> historiqueSessions { get; set; }
        public virtual DbSet<KPI> KPIs { get; set; }
        public virtual DbSet<ligneADSL> ligneADSLs { get; set; }
        public virtual DbSet<localite> localites { get; set; }
        public virtual DbSet<modem> modems { get; set; }
        public virtual DbSet<motif> motifs { get; set; }
        public virtual DbSet<reference> references { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<TypeReseau> TypeReseaux { get; set; }
        public virtual DbSet<historiqueKPI> historiqueKPIs { get; set; }
        public virtual DbSet<dailyParameter> dailyParameters { get; set; }
        public virtual DbSet<notexiste> notexistes { get; set; }
        public virtual DbSet<ticketGenere> ticketGeneres { get; set; }
    
        public virtual ObjectResult<carteGeoChartMoyConnexionNbPersonne_Result> carteGeoChartMoyConnexionNbPersonne()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<carteGeoChartMoyConnexionNbPersonne_Result>("carteGeoChartMoyConnexionNbPersonne");
        }
    
        public virtual ObjectResult<cherche_Result> cherche(Nullable<int> num)
        {
            var numParameter = num.HasValue ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cherche_Result>("cherche", numParameter);
        }
    
        public virtual int createTicket(Nullable<int> numsequence, Nullable<int> idMotif, string description)
        {
            var numsequenceParameter = numsequence.HasValue ?
                new ObjectParameter("numsequence", numsequence) :
                new ObjectParameter("numsequence", typeof(int));
    
            var idMotifParameter = idMotif.HasValue ?
                new ObjectParameter("idMotif", idMotif) :
                new ObjectParameter("idMotif", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createTicket", numsequenceParameter, idMotifParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<DetailBarreReference_Result> DetailBarreReference(Nullable<int> idReference)
        {
            var idReferenceParameter = idReference.HasValue ?
                new ObjectParameter("idReference", idReference) :
                new ObjectParameter("idReference", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetailBarreReference_Result>("DetailBarreReference", idReferenceParameter);
        }
    
        public virtual ObjectResult<DetailBarreReferenceAvecDate_Result> DetailBarreReferenceAvecDate(string nomKPI)
        {
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetailBarreReferenceAvecDate_Result>("DetailBarreReferenceAvecDate", nomKPIParameter);
        }
    
        public virtual ObjectResult<DetailBarreReferenceNbDeconnexion_Result> DetailBarreReferenceNbDeconnexion(Nullable<int> idReference)
        {
            var idReferenceParameter = idReference.HasValue ?
                new ObjectParameter("idReference", idReference) :
                new ObjectParameter("idReference", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetailBarreReferenceNbDeconnexion_Result>("DetailBarreReferenceNbDeconnexion", idReferenceParameter);
        }
    
        public virtual ObjectResult<historiqueConnexion_Result> historiqueConnexion(string userName, Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<historiqueConnexion_Result>("historiqueConnexion", userNameParameter, dateDebParameter, dateFinParameter);
        }
    
        public virtual ObjectResult<historiqueConnexionDetaille_Result> historiqueConnexionDetaille(string userName, Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<historiqueConnexionDetaille_Result>("historiqueConnexionDetaille", userNameParameter, dateDebParameter, dateFinParameter);
        }
    
        public virtual int insertReference(Nullable<int> bornDeb, Nullable<int> bornFin, Nullable<int> bornMoy, string nomKPI)
        {
            var bornDebParameter = bornDeb.HasValue ?
                new ObjectParameter("bornDeb", bornDeb) :
                new ObjectParameter("bornDeb", typeof(int));
    
            var bornFinParameter = bornFin.HasValue ?
                new ObjectParameter("bornFin", bornFin) :
                new ObjectParameter("bornFin", typeof(int));
    
            var bornMoyParameter = bornMoy.HasValue ?
                new ObjectParameter("bornMoy", bornMoy) :
                new ObjectParameter("bornMoy", typeof(int));
    
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertReference", bornDebParameter, bornFinParameter, bornMoyParameter, nomKPIParameter);
        }
    
        public virtual int insertTicket(Nullable<int> numsequence, Nullable<int> idMotif, string description)
        {
            var numsequenceParameter = numsequence.HasValue ?
                new ObjectParameter("numsequence", numsequence) :
                new ObjectParameter("numsequence", typeof(int));
    
            var idMotifParameter = idMotif.HasValue ?
                new ObjectParameter("idMotif", idMotif) :
                new ObjectParameter("idMotif", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertTicket", numsequenceParameter, idMotifParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<listeTicket_Result> listeTicket()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listeTicket_Result>("listeTicket");
        }
    
        public virtual ObjectResult<maxConnexionSemaineDynamicDate_Result> maxConnexionSemaineDynamicDate(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string gouvernerat)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var gouverneratParameter = gouvernerat != null ?
                new ObjectParameter("gouvernerat", gouvernerat) :
                new ObjectParameter("gouvernerat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<maxConnexionSemaineDynamicDate_Result>("maxConnexionSemaineDynamicDate", dateDebParameter, dateFinParameter, gouverneratParameter);
        }
    
        public virtual ObjectResult<string> maxDureeConnexionSemaine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maxDureeConnexionSemaine");
        }
    
        public virtual ObjectResult<string> maxDureeConnexionSemaineUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maxDureeConnexionSemaineUser", usernameParameter);
        }
    
        public virtual ObjectResult<minConnexionSemaineDynamicDate_Result> minConnexionSemaineDynamicDate(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string gouvernerat)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var gouverneratParameter = gouvernerat != null ?
                new ObjectParameter("gouvernerat", gouvernerat) :
                new ObjectParameter("gouvernerat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<minConnexionSemaineDynamicDate_Result>("minConnexionSemaineDynamicDate", dateDebParameter, dateFinParameter, gouverneratParameter);
        }
    
        public virtual int minDureeConnexionDynamique(string nomKPI, Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin)
        {
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("minDureeConnexionDynamique", nomKPIParameter, dateDebParameter, dateFinParameter);
        }
    
        public virtual ObjectResult<string> minDureeConnexionSemaine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("minDureeConnexionSemaine");
        }
    
        public virtual ObjectResult<string> minDureeConnexionSemaineUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("minDureeConnexionSemaineUser", usernameParameter);
        }
    
        public virtual int minDureeConnexionUserDynamique(string nomKPI, Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin)
        {
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("minDureeConnexionUserDynamique", nomKPIParameter, dateDebParameter, dateFinParameter);
        }
    
        public virtual int modifTicket(Nullable<int> numSequence, string description)
        {
            var numSequenceParameter = numSequence.HasValue ?
                new ObjectParameter("numSequence", numSequence) :
                new ObjectParameter("numSequence", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("modifTicket", numSequenceParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<moyDureeConnexionParJourParGouvernerat_Result> moyDureeConnexionParJourParGouvernerat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<moyDureeConnexionParJourParGouvernerat_Result>("moyDureeConnexionParJourParGouvernerat");
        }
    
        public virtual ObjectResult<moyDureeConnexionParJourParGouverneratHHmmSS_Result> moyDureeConnexionParJourParGouverneratHHmmSS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<moyDureeConnexionParJourParGouverneratHHmmSS_Result>("moyDureeConnexionParJourParGouverneratHHmmSS");
        }
    
        public virtual ObjectResult<string> moyDureeConnexionSemaine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("moyDureeConnexionSemaine");
        }
    
        public virtual ObjectResult<moyDureeConnexionSemaineDynamicDate_Result> moyDureeConnexionSemaineDynamicDate(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string gouvernerat)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var gouverneratParameter = gouvernerat != null ?
                new ObjectParameter("gouvernerat", gouvernerat) :
                new ObjectParameter("gouvernerat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<moyDureeConnexionSemaineDynamicDate_Result>("moyDureeConnexionSemaineDynamicDate", dateDebParameter, dateFinParameter, gouverneratParameter);
        }
    
        public virtual ObjectResult<string> moyDureeConnexionSemaineUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("moyDureeConnexionSemaineUser", usernameParameter);
        }
    
        public virtual ObjectResult<moyNbDeconnexionSemaineParGouvernerat_Result> moyNbDeconnexionSemaineParGouvernerat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<moyNbDeconnexionSemaineParGouvernerat_Result>("moyNbDeconnexionSemaineParGouvernerat");
        }
    
        public virtual ObjectResult<Nullable<int>> moyNBdeonnexionSemaine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("moyNBdeonnexionSemaine");
        }
    
        public virtual ObjectResult<moyNBdeonnexionSemaineDynamicDate_Result> moyNBdeonnexionSemaineDynamicDate(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string gouvernerat)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var gouverneratParameter = gouvernerat != null ?
                new ObjectParameter("gouvernerat", gouvernerat) :
                new ObjectParameter("gouvernerat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<moyNBdeonnexionSemaineDynamicDate_Result>("moyNBdeonnexionSemaineDynamicDate", dateDebParameter, dateFinParameter, gouverneratParameter);
        }
    
        public virtual ObjectResult<moyNBdeonnexionSemaineDynamicGouvernerat_Result> moyNBdeonnexionSemaineDynamicGouvernerat(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<moyNBdeonnexionSemaineDynamicGouvernerat_Result>("moyNBdeonnexionSemaineDynamicGouvernerat", dateDebParameter, dateFinParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> moyNBdeonnexionSemaineUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("moyNBdeonnexionSemaineUser", usernameParameter);
        }
    
        public virtual ObjectResult<moySessionDeconnexionSemaine_Result> moySessionDeconnexionSemaine()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<moySessionDeconnexionSemaine_Result>("moySessionDeconnexionSemaine");
        }
    
        public virtual ObjectResult<referenceDureeMaximalConnexion_Result> referenceDureeMaximalConnexion(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string userName)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<referenceDureeMaximalConnexion_Result>("referenceDureeMaximalConnexion", dateDebParameter, dateFinParameter, userNameParameter);
        }
    
        public virtual ObjectResult<referenceDureeMinimalConnexion_Result> referenceDureeMinimalConnexion(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string userName)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<referenceDureeMinimalConnexion_Result>("referenceDureeMinimalConnexion", dateDebParameter, dateFinParameter, userNameParameter);
        }
    
        public virtual ObjectResult<referenceDureeMoyenneConnexion_Result> referenceDureeMoyenneConnexion(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string userName)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<referenceDureeMoyenneConnexion_Result>("referenceDureeMoyenneConnexion", dateDebParameter, dateFinParameter, userNameParameter);
        }
    
        public virtual ObjectResult<referenceKPIDureeMaximale_Result> referenceKPIDureeMaximale(string nomKPI)
        {
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<referenceKPIDureeMaximale_Result>("referenceKPIDureeMaximale", nomKPIParameter);
        }
    
        public virtual ObjectResult<referenceKPIDureeMinimale_Result> referenceKPIDureeMinimale(string nomKPI)
        {
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<referenceKPIDureeMinimale_Result>("referenceKPIDureeMinimale", nomKPIParameter);
        }
    
        public virtual ObjectResult<referenceKPINbDeconnexion_Result> referenceKPINbDeconnexion(string nomKPI)
        {
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<referenceKPINbDeconnexion_Result>("referenceKPINbDeconnexion", nomKPIParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> referenceNbDeconnexionConnexion(Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string userName)
        {
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("referenceNbDeconnexionConnexion", dateDebParameter, dateFinParameter, userNameParameter);
        }
    
        public virtual ObjectResult<sessionTime_Result> sessionTime(string userName, Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sessionTime_Result>("sessionTime", userNameParameter, dateDebParameter, dateFinParameter);
        }
    
        public virtual int sumNbDeconnexionGlobal(string gouvernerat, Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin, string nomKPI)
        {
            var gouverneratParameter = gouvernerat != null ?
                new ObjectParameter("gouvernerat", gouvernerat) :
                new ObjectParameter("gouvernerat", typeof(string));
    
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sumNbDeconnexionGlobal", gouverneratParameter, dateDebParameter, dateFinParameter, nomKPIParameter);
        }
    
        public virtual ObjectResult<test_Result> test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Result>("test");
        }
    
        public virtual ObjectResult<testdes_Result> testdes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<testdes_Result>("testdes");
        }
    
        public virtual ObjectResult<testnotEXISTE_Result> testnotEXISTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<testnotEXISTE_Result>("testnotEXISTE");
        }
    
        public virtual ObjectResult<ticketdate_Result> ticketdate(Nullable<System.DateTime> date1, Nullable<System.DateTime> date2)
        {
            var date1Parameter = date1.HasValue ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(System.DateTime));
    
            var date2Parameter = date2.HasValue ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ticketdate_Result>("ticketdate", date1Parameter, date2Parameter);
        }
    
        public virtual int USERkpi(string userName, string nomKPI, Nullable<System.DateTime> dateDeb, Nullable<System.DateTime> dateFin)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var nomKPIParameter = nomKPI != null ?
                new ObjectParameter("nomKPI", nomKPI) :
                new ObjectParameter("nomKPI", typeof(string));
    
            var dateDebParameter = dateDeb.HasValue ?
                new ObjectParameter("dateDeb", dateDeb) :
                new ObjectParameter("dateDeb", typeof(System.DateTime));
    
            var dateFinParameter = dateFin.HasValue ?
                new ObjectParameter("dateFin", dateFin) :
                new ObjectParameter("dateFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USERkpi", userNameParameter, nomKPIParameter, dateDebParameter, dateFinParameter);
        }
    }
}
