//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topnet_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reference
    {
        public int idReference { get; set; }
        public Nullable<int> borneDebut { get; set; }
        public Nullable<int> borneFin { get; set; }
        public Nullable<int> borneMoyenne { get; set; }
        public int idKPI { get; set; }
        public Nullable<System.DateTime> dateReference { get; set; }
        public string nomReference { get; set; }
    
        public virtual KPI KPI { get; set; }
    }
}
